DefaultContentLanguage = "en"
author = "Steve Francia"
baseURL = "https://gohugo.io/"
copyright = "Copyright © MKT ID"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "github.com/jonathanjanssens/hugo-casper3"
title = "Hugo Themes"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "github-repo-theme"
name = "Get Theme on Github"
url = "https://github.com/jonathanjanssens/hugo-casper3"
weight = 30
[[menu.main]]
identifier = "author"
name = "Author Homepage"
url = "https://jonathanjanssens.com"
weight = 40
[params]
description = "Demo MKT ID"
facebook = ""
github = ""
logo = "/images/blogdeprueba.PNG"
mainSections = ["post"]
twitter = ""
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = false
[services.twitter]
disableInlineCSS = false
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
